[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo ='flazz/vim-colorschemes'

[[plugins]]
repo = 'scrooloose/nerdtree'
